import json
from Installation import Installation

installation = open('../data_installation.json')
data_installation = json.load(installation)

for elem in data_installation["data"]:
	monInstallation = Installation(elem["ComInsee"])
	monInstallation.setComLib(elem["ComLib"])
	monInstallation.setInsAccessibiliteAucun(elem["InsAccessibiliteAucun"])
	monInstallation.setInsAccessibiliteHandiMoteur(elem["InsAccessibiliteHandiMoteur"])
	monInstallation.setInsAccessibiliteHandiSens(elem["InsAccessibiliteHandiSens"])
	monInstallation.setInsCodePostal(elem["InsCodePostal"])
	monInstallation.setInsDateMaj(elem["InsDateMaj"])
	monInstallation.setInsEmpriseFonciere(elem["InsEmpriseFonciere"])
	monInstallation.setInsGardiennee(elem["InsGardiennee"])
	monInstallation.setInsLibelleVoie(elem["InsLibelleVoie"])
	monInstallation.setInsLieuDit(elem["InsLieuDit"])
	monInstallation.setInsMultiCommune(elem["InsMultiCommune"])
	monInstallation.setInsNbPlaceParking(elem["InsNbPlaceParking"])
	monInstallation.setInsNbPlaceParkingHandi(elem["InsNbPlaceParkingHandi"])
	monInstallation.setInsNoVoie(elem["InsNoVoie"])
	monInstallation.setInsNumeroInstall(elem["InsNumeroInstall"])
	monInstallation.setInsPartLibelle(elem["InsPartLibelle"])
	monInstallation.setInsTransportAutre(elem["InsTransportAutre"])
	monInstallation.setInsTransportBateau(elem["InsTransportBateau"])
	monInstallation.setInsTransportBus(elem["InsTransportBus"])
	monInstallation.setInsTransportMetro(elem["InsTransportMetro"])
	monInstallation.setInsTransportTrain(elem["InsTransportTrain"])
	monInstallation.setInsTransportTram(elem["InsTransportTram"])
	monInstallation.setLatitude(elem["Latitude"])
	monInstallation.setLongitude(elem["Longitude"])
	monInstallation.setNb_Equipements(elem["Nb_Equipements"])
	monInstallation.setNb_FicheEquipement(elem["Nb_FicheEquipement"])
	monInstallation.set_l(elem["_l"])
	monInstallation.setGeo(elem["geo"])   

	print (monInstallation)